In [ ]:
# default_exp embeddings

# Embeddings
> AdaptNLP Embeddings Module

In [ ]:
#hide
from nbdev.showdoc import *
from fastcore.test import test_eq
from fastcore.xtras import is_listy

In [ ]:
#export
import logging, torch
from typing import List, Dict, Union
from collections import defaultdict, OrderedDict

from fastcore.basics import mk_class
from fastcore.xtras import dict2obj
from fastcore.dispatch import typedispatch
from flair.data import Sentence
from flair.embeddings import (
    Embeddings,
    WordEmbeddings,
    StackedEmbeddings,
    FlairEmbeddings,
    DocumentPoolEmbeddings,
    DocumentRNNEmbeddings,
    TransformerWordEmbeddings,
)

from adaptnlp.model_hub import FlairModelHub, HFModelHub, FlairModelResult, HFModelResult

In [ ]:
#export
_flair_hub = FlairModelHub()
_hf_hub = HFModelHub()

In [ ]:
#export
logger = logging.getLogger(__name__)

In [ ]:
#exporti
@typedispatch
def _make_sentences(text:str, as_list=False) -> Union[List[Sentence], Sentence]:
    return [Sentence(text)] if as_list else Sentence(text)

In [ ]:
#hide
test_sentences = 'a,b,c'.split(',')
out = _make_sentences(test_sentences)
tst_out = [Sentence('a'), Sentence('b'), Sentence('c')]
for o,t in zip(out, tst_out):
    test_eq(o[0].text, t[0].text)

In [ ]:
#exporti
@typedispatch
def _make_sentences(text:list, as_list=False) -> Union[List[Sentence], Sentence]:
    if all(isinstance(t,str) for t in text):
        return [Sentence(t) for t in text]
    elif all(isinstance(t, Sentence) for t in text):
        return text

In [ ]:
#hide
test_sentence = 'My name is Zach'
out = _make_sentences(test_sentence, as_list=True)
tst_out = [Sentence(test_sentence)]
for o,t in zip(out, tst_out):
    test_eq(o[0].text, t[0].text)
test_eq(is_listy(out), True)

In [ ]:
#exporti
@typedispatch
def _make_sentences(text:Sentence, as_list=False) -> Union[List[Sentence], Sentence]:
    return [text] if as_list else text

In [ ]:
#hide
test_sentence = Sentence('Me')
out = _make_sentences(test_sentence)
test_eq(test_sentence[0].text, out[0].text)

In [ ]:
#exporti
def _get_embedding_model(model_name_or_path:Union[str, HFModelResult, FlairModelResult]) -> Union[FlairEmbeddings, WordEmbeddings, TransformerWordEmbeddings, Sentence]:
    "Load the proper `Embeddings` model from `model_name_or_path`"
    if isinstance(model_name_or_path, FlairModelResult): 
        nm = model_name_or_path.name
        try:
            return WordEmbeddings(nm.strip('flairNLP/'))
        except:
            return FlairEmbeddings(nm.strip('flairNLP/'))
    
    elif isinstance(model_name_or_path, HFModelResult): return TransformerWordEmbeddings(model_name_or_path.name)
    else:
        res = _flair_hub.search_model_by_name(model_name_or_path, user_uploaded=True)
        if len(res) < 1:
            # No models found
            res = _hf_hub.search_model_by_name(model_name_or_path, user_uploaded=True)
            if len(res) < 1:
                raise ValueError(f'Embeddings not found for the model key: {model_name_or_path}, check documentation or custom model path to verify specified model')
            else:
                return TransformerWordEmbeddings(res[0].name) # Returning the first should always be the non-fast option
        else:
            nm = res[0].name
            try:
                return WordEmbeddings(nm.strip('flairNLP/'))
            except:
                return FlairEmbeddings(nm.strip('flairNLP/'))

In [ ]:
#export
mk_class('DetailLevel', **{o:o.lower() for o in 'High,Medium,Low'.split(',')},
         doc="All possible naming conventions for DetailLevel with typo-proofing")

In [ ]:
#export
class EmbeddingResult:
    """
    A result class designed for Embedding models
    """
    def __init__(self, sentence:Sentence):
        self._sentence = sentence
    
    @property
    def sentence_embeddings(self) -> torch.tensor:
        """
        All embeddings in `sentence` (if available)
        """
        return self._sentence.get_embedding()
    
    @property
    def token_embeddings(self) -> torch.tensor:
        """
        All embeddings from the individual tokens in `sentence` with original order in shape (n, embed_dim)
        """
        return torch.stack([tok.get_embedding() for tok in self._sentence], dim=0)

    @property
    def tokenized_inputs(self) -> str:
        """
        The original tokenized inputs
        """
        return self._sentence.to_tokenized_string()
    
    @property
    def inputs(self) -> str:
        """
        The original input
        """
        return self._sentence.to_original_text()
    
    def to_dict(self, detail_level:DetailLevel=DetailLevel.Low):
        o = OrderedDict()
        o.update({'inputs':self.inputs,
                  'sentence_embeddings':self.sentence_embeddings,
                 'token_embeddings':self.token_embeddings})
        if detail_level == 'medium' or detail_level == 'high':
            # Return embeddings/word pairs and indicies, and the tokenized input
            o.update({
                tok.text:{
                    'embeddings':tok.get_embedding(),
                    'word_idx':tok.idx
                } for tok in self._sentence
            })
            o.update({
                'tokenized_inputs':self.tokenized_inputs
            })
        if detail_level == 'high':
            # Return embeddings/word pairs, indicies, and the original Sentence object
            o.update({tok.text:{
                'embeddings':tok.get_embedding(),
                'word_idx':tok.idx
                } for tok in self._sentence})
            o.update({'sentence':self._sentence})
        return o
    
    def __repr__(self):
        s = f"{self.__class__.__name__}:" + " {"
        s += f'\n\tInputs: {self.inputs}'
        if self.token_embeddings is not None: s += f'\n\tToken Embeddings Shape: {self.token_embeddings.shape}'
        if self.sentence_embeddings is not None: s += f'\n\tSentence Embeddings Shape: {self.sentence_embeddings.shape}'
        return s + '\n}'

In [ ]:
#exporti
def _format_results(embeds:list, detail_level:DetailLevel=None):
    """
    Generates either a list of `EmbeddingResult`s or a single based upon `detail_level` and their length
    """
    res = [EmbeddingResult(embed) for embed in embeds]
    return [o.to_dict(detail_level) for o in res] if detail_level is not None else res

In [ ]:
#export
class EasyWordEmbeddings:
    """Word embeddings from the latest language models

    Usage:

    ```python
    >>> embeddings = adaptnlp.EasyWordEmbeddings()
    >>> embeddings.embed_text("text you want embeddings for", model_name_or_path="bert-base-cased")
    ```
    """

    def __init__(self):
        self.models: Dict[Embeddings] = defaultdict(bool)

    def embed_text(
        self,
        text: Union[List[Sentence], Sentence, List[str], str],
        model_name_or_path: Union[str, HFModelResult, FlairModelResult] = "bert-base-cased",
        detail_level:DetailLevel = DetailLevel.Low,
        raw:bool = False
    ) -> List[EmbeddingResult]:
        """Produces embeddings for text

        **Parameters**:
        * `text` - Text input, it can be a string or any of Flair's `Sentence` input formats
        * `model_name_or_path` - The hosted model name key, model path, or an instance of either `HFModelResult` or `FlairModelResult`
        * `detail_level` - A level of detail to return. By default is None, which returns a EmbeddingResult, otherwise will return a dict
        * `raw` - A boolean of whether to skip generating an EmbeddingResult or dictionary. Mostly for dev, default is False
        
        **Return**:
        * A list of either EmbeddingResult's or dictionaries with information
        """
        # Convert into sentences
        sentences = _make_sentences(text)

        # Load correct Embeddings module
        self.models[model_name_or_path] = _get_embedding_model(model_name_or_path)
        embedding = self.models[model_name_or_path]
        embeds = embedding.embed(sentences)
        
        return _format_results(embeds, detail_level) if not raw else embeds

    def embed_all(
        self,
        text: Union[List[Sentence], Sentence, List[str], str],
        model_names_or_paths:List[str] = [],
        detail_level:DetailLevel=DetailLevel.Low,
        raw:bool = False,
    ) -> List[EmbeddingResult]:
        """Embeds text with all embedding models loaded

        **Parameters**:
        * `text` - Text input, it can be a string or any of Flair's `Sentence` input formats
        * `model_names_or_paths` -  A list of model names
        * `detail_level` - A level of detail to return. By default is None, which returns a EmbeddingResult, otherwise will return a dict
        * `raw` - A boolean of whether to skip generating an EmbeddingResult or dictionary. Mostly for dev, default is False
        
        **Return**:
        * A list of either EmbeddingResult's or dictionaries with information
        """
        # Convert into sentences
        sentences = _make_sentences(text)

        if model_names_or_paths:
            for embedding_name in model_names_or_paths:
                sentences = self.embed_text(
                    sentences, model_name_or_path=embedding_name, raw=True
                )
        else:
            for embedding_name in self.models.keys():
                sentences = self.embed_text(
                    sentences, model_name_or_path=embedding_name, raw=True
                )
        return _format_results(sentences, detail_level) if not raw else embeds

In [ ]:
#hide
import torch
embeddings = EasyWordEmbeddings()
res = embeddings.embed_text("text you want embeddings for", model_name_or_path="bert-base-cased")
test_eq(res[0]['token_embeddings'].shape, torch.Size([5, 768]))

Some weights of the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
#hide
res

[OrderedDict([('inputs', 'text you want embeddings for'),
              ('sentence_embeddings', tensor([])),
              ('token_embeddings',
               tensor([[-7.9327e-01, -4.1105e-01, -3.8680e-01,  ..., -3.2171e-01,
                         3.0939e-01,  4.4718e-01],
                       [ 8.5489e-01, -3.2192e-01,  3.8047e-01,  ...,  9.5253e-01,
                        -1.2863e-01,  5.8812e-01],
                       [-2.1384e-02,  4.0351e-01, -1.6811e-01,  ...,  3.7693e-01,
                        -1.0005e+00,  1.1159e-01],
                       [ 4.2309e-01,  1.2025e+00, -7.9792e-01,  ...,  1.2090e-01,
                         1.4435e+00,  1.2092e-03],
                       [-1.8945e-01,  7.2156e-02, -6.4450e-01,  ..., -4.3372e-01,
                        -1.9544e-01, -2.6331e-01]], device='cuda:0'))])]

In [ ]:
#hide
res = embeddings.embed_all(['text you want embeddings for', 'My name is Zach'],
                           ['bert-base-cased', 'xlnet-base-cased'])
test_eq(res[0]['token_embeddings'].shape, torch.Size([5,1536]))

Some weights of the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetModel: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if y

In [ ]:
#hide
res

[OrderedDict([('inputs', 'text you want embeddings for'),
              ('sentence_embeddings', tensor([])),
              ('token_embeddings',
               tensor([[-0.7933, -0.4110, -0.3868,  ..., -0.3953, -0.7718,  0.1248],
                       [ 0.8549, -0.3219,  0.3805,  ..., -0.7219,  0.8176,  0.1700],
                       [-0.0214,  0.4035, -0.1681,  ..., -0.7486,  0.8592,  0.6758],
                       [ 0.4231,  1.2025, -0.7979,  ..., -0.6044,  0.1577,  0.8191],
                       [-0.1894,  0.0722, -0.6445,  ..., -1.1703, -0.3907,  0.2863]],
                      device='cuda:0'))]),
 OrderedDict([('inputs', 'My name is Zach'),
              ('sentence_embeddings', tensor([])),
              ('token_embeddings',
               tensor([[-0.6113,  0.4488,  0.1556,  ..., -0.6987, -0.6393, -0.4213],
                       [-0.4969,  0.8494,  0.0863,  ..., -0.2641, -0.5141,  0.4813],
                       [-0.5020, -0.2093,  0.2883,  ..., -0.8309,  0.6171,  0.1118],
 

In [ ]:
#export
class EasyStackedEmbeddings:
    """Word Embeddings that have been concatenated and "stacked" as specified by flair

    Usage:

    ```python
    >>> embeddings = adaptnlp.EasyStackedEmbeddings("bert-base-cased", "gpt2", "xlnet-base-cased")
    ```

    **Parameters:**

    * `embeddings` - Non-keyword variable number of strings specifying the embeddings you want to stack
    """

    def __init__(self, *embeddings: str):
        print("May need a couple moments to instantiate...")
        self.embedding_stack = []

        # Load correct Embeddings module
        for model_name_or_path in embeddings:
            self.embedding_stack.append(_get_embedding_model(model_name_or_path))

        assert len(self.embedding_stack) != 0
        self.stacked_embeddings = StackedEmbeddings(embeddings=self.embedding_stack)

    def embed_text(
        self,
        text: Union[List[Sentence], Sentence, List[str], str],
        detail_level:DetailLevel = DetailLevel.Low,
        raw:bool = False
    ) -> List[EmbeddingResult]:
        """Stacked embeddings

        **Parameters**:
        * `text` - Text input, it can be a string or any of Flair's `Sentence` input formats
        * `detail_level` - A level of detail to return. By default is None, which returns a EmbeddingResult, otherwise will return a dict
        * `raw` - A boolean of whether to skip generating an EmbeddingResult or dictionary. Mostly for dev, default is False

        **Return**:
        * A list of either EmbeddingResult's or dictionaries with information
        """
        # Convert into sentences
        sentences = _make_sentences(text, as_list=True)

        # Unlike flair embeddings modules, stacked embeddings do not return a list of sentences
        self.stacked_embeddings.embed(sentences)
        
        return _format_results(sentences, detail_level) if not raw else embeds

In [ ]:
#hide
embeddings = EasyStackedEmbeddings("bert-base-cased", "xlnet-base-cased")
sentences = embeddings.embed_text("This is Albert.  My last name is Einstein.  I like physics and atoms.")
test_eq(sentences[0]['token_embeddings'].shape, torch.Size([16,1536]))

May need a couple moments to instantiate...


Some weights of the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetModel: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if y

In [ ]:
#hide
sentences

[OrderedDict([('inputs',
               'This is Albert.  My last name is Einstein.  I like physics and atoms.'),
              ('sentence_embeddings', tensor([])),
              ('token_embeddings',
               tensor([[-0.6795, -0.2041,  1.0153,  ...,  0.4284, -1.7024, -0.2833],
                       [-0.1609, -0.2013,  0.9313,  ...,  0.1025, -0.6252, -0.4562],
                       [-0.0846, -0.2399,  0.2524,  ...,  0.1644,  0.0220,  0.1787],
                       ...,
                       [ 0.2307,  0.0850, -0.3529,  ...,  0.3358,  0.3527,  0.3798],
                       [-0.3223,  0.3806, -0.7739,  ..., -0.0810,  0.4421,  0.2971],
                       [ 0.2760, -0.0849, -0.0120,  ...,  0.2688,  0.4413,  0.1424]],
                      device='cuda:0'))])]

In [ ]:
#export
class EasyDocumentEmbeddings:
    """Document Embeddings generated by pool and rnn methods applied to the word embeddings of text

    Usage:

    ```python
    >>> embeddings = adaptnlp.EasyDocumentEmbeddings("bert-base-cased", "xlnet-base-cased", methods["rnn"])
    ```

    **Parameters:**

    * `embeddings` - Non-keyword variable number of strings referring to model names or paths
    * `methods` - A list of strings to specify which document embeddings to use i.e. ["rnn", "pool"] (avoids unncessary loading of models if only using one)
    * `configs` - A dictionary of configurations for flair's rnn and pool document embeddings
    ```python
    >>> example_configs = {"pool_configs": {"fine_tune_mode": "linear", "pooling": "mean", },
    ...                   "rnn_configs": {"hidden_size": 512,
    ...                                   "rnn_layers": 1,
    ...                                   "reproject_words": True,
    ...                                   "reproject_words_dimension": 256,
    ...                                   "bidirectional": False,
    ...                                   "dropout": 0.5,
    ...                                   "word_dropout": 0.0,
    ...                                   "locked_dropout": 0.0,
    ...                                   "rnn_type": "GRU",
    ...                                   "fine_tune": True, },
    ...                  }
    ```
    """

    __allowed_methods = ["rnn", "pool"]
    __allowed_configs = ("pool_configs", "rnn_configs")

    def __init__(
        self,
        *embeddings: str,
        methods: List[str] = ["rnn", "pool"],
        configs: Dict = {
            "pool_configs": {"fine_tune_mode": "linear", "pooling": "mean"},
            "rnn_configs": {
                "hidden_size": 512,
                "rnn_layers": 1,
                "reproject_words": True,
                "reproject_words_dimension": 256,
                "bidirectional": False,
                "dropout": 0.5,
                "word_dropout": 0.0,
                "locked_dropout": 0.0,
                "rnn_type": "GRU",
                "fine_tune": True,
            },
        },
    ):
        print("May need a couple moments to instantiate...")
        self.embedding_stack = []

        # Check methods
        for m in methods:
            assert m in self.__class__.__allowed_methods

        # Set configs for pooling and rnn parameters
        for k, v in configs.items():
            assert k in self.__class__.__allowed_configs
            setattr(self, k, v)

        # Load correct Embeddings module
        for model_name_or_path in embeddings:
            self.embedding_stack.append(_get_embedding_model(model_name_or_path))

        assert len(self.embedding_stack) != 0
        if "pool" in methods:
            self.pool_embeddings = DocumentPoolEmbeddings(
                self.embedding_stack, **self.pool_configs
            )
            print("Pooled embedding loaded")
        if "rnn" in methods:
            self.rnn_embeddings = DocumentRNNEmbeddings(
                self.embedding_stack, **self.rnn_configs
            )
            print("RNN embeddings loaded")

    def embed_pool(
        self,
        text: Union[List[Sentence], Sentence, List[str], str],
        detail_level:DetailLevel = DetailLevel.Low,
    ) -> List[EmbeddingResult]:
        """Generate stacked embeddings with `DocumentPoolEmbeddings`

        **Parameters**:
        * `text` - Text input, it can be a string or any of Flair's `Sentence` input formats
        * `detail_level` - A level of detail to return. By default is None, which returns a EmbeddingResult, otherwise will return a dict

        **Return**:
        * A list of either EmbeddingResult's or dictionaries with information
        """
        sentences = _make_sentences(text, as_list=True)
        self.pool_embeddings.embed(sentences)
        return _format_results(sentences, detail_level)

    def embed_rnn(
        self,
        text: Union[List[Sentence], Sentence, List[str], str],
        detail_level:DetailLevel = DetailLevel.Low,
    ) -> List[Sentence]:
        """Generate stacked embeddings with `DocumentRNNEmbeddings`

        **Parameters**:
        * `text` - Text input, it can be a string or any of Flair's `Sentence` input formats
        * `detail_level` - A level of detail to return. By default is None, which returns a EmbeddingResult, otherwise will return a dict

        **Return**:
        * A list of either EmbeddingResult's or dictionaries with information
        """
        sentences = _make_sentences(text, as_list=True)
        self.rnn_embeddings.embed(sentences)
        return _format_results(sentences, detail_level)

In [ ]:
#hide
embeddings = EasyDocumentEmbeddings("bert-base-cased", "xlnet-base-cased")
res = embeddings.embed_pool("This is Albert.  My last name is Einstein.  I like physics and atoms.")
test_eq(res[0]['sentence_embeddings'].shape, torch.Size([1536]))

May need a couple moments to instantiate...


Some weights of the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetModel: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if y

Pooled embedding loaded
RNN embeddings loaded


In [ ]:
#hide
res

[OrderedDict([('inputs',
               'This is Albert.  My last name is Einstein.  I like physics and atoms.'),
              ('sentence_embeddings',
               tensor([-0.2397,  0.2154,  0.1053,  ..., -0.0263, -0.2341,  0.0857],
                      device='cuda:0', grad_fn=<CatBackward>)),
              ('token_embeddings',
               tensor([[-0.6795, -0.2041,  1.0153,  ...,  0.4284, -1.7024, -0.2833],
                       [-0.1609, -0.2013,  0.9313,  ...,  0.1025, -0.6252, -0.4562],
                       [-0.0846, -0.2399,  0.2524,  ...,  0.1644,  0.0220,  0.1787],
                       ...,
                       [ 0.2307,  0.0850, -0.3529,  ...,  0.3358,  0.3527,  0.3798],
                       [-0.3223,  0.3806, -0.7739,  ..., -0.0810,  0.4421,  0.2971],
                       [ 0.2760, -0.0849, -0.0120,  ...,  0.2688,  0.4413,  0.1424]],
                      device='cuda:0'))])]

In [ ]:
#hide
res = embeddings.embed_rnn("This is Albert.  My last name is Einstein.  I like physics and atoms.")
test_eq(res[0]['sentence_embeddings'].shape, torch.Size([512]))

In [ ]:
#hide
res

[OrderedDict([('inputs',
               'This is Albert.  My last name is Einstein.  I like physics and atoms.'),
              ('sentence_embeddings',
               tensor([-0.1714, -0.7549, -0.1850, -0.2769,  0.2418, -0.4486,  0.6229, -0.6479,
                        0.6507, -0.1576, -0.2320,  0.2510,  0.7094, -0.5881, -0.1548, -0.1689,
                       -0.4031, -0.5152,  0.8924,  0.2729, -0.5003, -0.5212, -0.1039,  0.4079,
                        0.3397, -0.3155,  0.0047,  0.1113, -0.0592, -0.3699, -0.6757, -0.2822,
                        0.3281, -0.0072, -0.8087, -0.1867, -0.3111,  0.1156,  0.1645, -0.4168,
                       -0.3203,  0.1876, -0.0131, -0.1157,  0.0309, -0.5008,  0.4087,  0.2558,
                        0.8947,  0.2512, -0.7544, -0.1717,  0.2814, -0.4354, -0.3502, -0.2949,
                        0.8499,  0.2330, -0.6120,  0.0607,  0.2288,  0.2005, -0.5318, -0.0992,
                        0.6384, -0.1772,  0.5373,  0.4454, -0.1449,  0.1644, -0.7993, -0